### ISSUE TITLE
"GetNowBlock" got an error

### ISSUE THREAD

**Issue by cjqpker** [tronprotocol/go-client-api#3]
got "rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: bad wiretype for field core.TransactionRaw.Type: got wiretype 2, want 0" when calling to "go-client-api.GetNowBlock".
maybe you forget to update go-client-api when upgrading tron

**Comment by sasaxie** [comment]
Thanks for your issue! It hasn't been implemented yet.
